// apps/web/src/lib/components/layouts/mainpage.svelte
<!--
DriveLite - The self-hostable file storage solution.
Copyright (C) 2025  

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
	import { Footer, Header } from '../common';

	let { children } = $props();
</script>

<Header />
<main>
	{@render children?.()}
</main>
<Footer />

// landing_page/src/UI/mainpage/MainPage.tsx
// DriveLite - The self-hostable file storage solution.
// Copyright (C) 2025  
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

 

import FeatureSection from "./FeatureSection";
import HeroSection from "./HeroSection";
import OSSSection from "./OSSSection";
import WaitlistSection from "./WailtistSection";

export default function MainPage() {
  return (
    <>
      <HeroSection />
      <FeatureSection />
      <OSSSection />
      <WaitlistSection />
    </>
  );
}
